### PR TITLE
Bump font awesome version

### PR DESCRIPTION
**Pull request by bobschi**
Hi @vidhill,

I need a newer version of Font Awesome Brands for work, so I decided to stop by and bump it's version. :)

### CODE REVIEW

**Review by vidhill — COMMENTED** [review]
I made a snafoo with the order merging, and got a merge conflict, so I included your changes on another PR: https://github.com/vidhill/fortawesome-brands-svg-11ty-shortcode/pull/11

**Comment by vidhill** [comment]
https://github.com/vidhill/fortawesome-brands-svg-11ty-shortcode/pull/9#pullrequestreview-2102956591

**Comment by vidhill** [comment]
@bobschi thanks again,

New release with your changes published to npm
https://www.npmjs.com/package/@vidhill/fortawesome-brands-11ty-shortcode?activeTab=versions

**Comment by bobschi** [comment]
> I made a snafoo with the order merging, and got a merge conflict, so I included your changes on another PR: #11

I could have also left a note about the other changes. 🙈
Thanks a ton for your work 😄

**Pull request closed without merging**
